### ISSUE TITLE
rearrangeMatrix() fails when matF contains NA

### ISSUE THREAD

**Issue by tdjames1** [jonesor/compadreDB#15] opened 2017-07-11 10:20 UTC
<a href="https://github.com/tdjames1"><img src="https://avatars0.githubusercontent.com/u/10053102?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [tdjames1](https://github.com/tdjames1)**
_Wednesday Jun 28, 2017 at 16:07 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_
_Originally opened as https://github.com/tdjames1/compadreDB/issues/7_

----

Example from Bernt-Erik Sæther, Øvind Bakke. 2000. Life history variation and contribution of different demographic traits to the population growth rate in birds: a comparative approach. Ecology 81: 642-653.
```
 saetherMatrices$`Diomedea exulans`
      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11]
 [1,] 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00  0.00    NA
 [2,] 0.92 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00  0.00  0.00
 [3,] 0.00 0.92 0.00 0.00 0.00 0.00 0.00 0.00 0.00  0.00  0.00
 [4,] 0.00 0.00 0.92 0.00 0.00 0.00 0.00 0.00 0.00  0.00  0.00
 [5,] 0.00 0.00 0.00 0.92 0.00 0.00 0.00 0.00 0.00  0.00  0.00
 [6,] 0.00 0.00 0.00 0.00 0.92 0.00 0.00 0.00 0.00  0.00  0.00
 [7,] 0.00 0.00 0.00 0.00 0.00 0.92 0.00 0.00 0.00  0.00  0.00
 [8,] 0.00 0.00 0.00 0.00 0.00 0.00 0.92 0.00 0.00  0.00  0.00
 [9,] 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.92 0.00  0.00  0.00
[10,] 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.92  0.00  0.00
[11,] 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00  0.92  0.92
```

Decomposed using values above the diagonal as the fecundity matrix, remaining values as growth/transition.

```
[1] "Species:  Diomedea exulans"
      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11]
 [1,]    0    0    0    0    0    0    0    0    0     0    NA
 [2,]    0    0    0    0    0    0    0    0    0     0     0
 [3,]    0    0    0    0    0    0    0    0    0     0     0
 [4,]    0    0    0    0    0    0    0    0    0     0     0
 [5,]    0    0    0    0    0    0    0    0    0     0     0
 [6,]    0    0    0    0    0    0    0    0    0     0     0
 [7,]    0    0    0    0    0    0    0    0    0     0     0
 [8,]    0    0    0    0    0    0    0    0    0     0     0
 [9,]    0    0    0    0    0    0    0    0    0     0     0
[10,]    0    0    0    0    0    0    0    0    0     0     0
[11,]    0    0    0    0    0    0    0    0    0     0     0
      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11]
 [1,] 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00  0.00  0.00
 [2,] 0.92 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00  0.00  0.00
 [3,] 0.00 0.92 0.00 0.00 0.00 0.00 0.00 0.00 0.00  0.00  0.00
 [4,] 0.00 0.00 0.92 0.00 0.00 0.00 0.00 0.00 0.00  0.00  0.00
 [5,] 0.00 0.00 0.00 0.92 0.00 0.00 0.00 0.00 0.00  0.00  0.00
 [6,] 0.00 0.00 0.00 0.00 0.92 0.00 0.00 0.00 0.00  0.00  0.00
 [7,] 0.00 0.00 0.00 0.00 0.00 0.92 0.00 0.00 0.00  0.00  0.00
 [8,] 0.00 0.00 0.00 0.00 0.00 0.00 0.92 0.00 0.00  0.00  0.00
 [9,] 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.92 0.00  0.00  0.00
[10,] 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.92  0.00  0.00
[11,] 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00  0.92  0.92
Error in Rep[1]:Rep[length(Rep)] : argument of length 0
```

**Comment by jonesor** [comment] 2017-07-17 10:36
The problem is with your matFmu matrix, not the F matrix.
1) Therefore, do you think it is best fixed during the stage when you calculate the Fmu matrix rather than in the function itself? (though a warning/error check would be good).

2) If this is to be resolved in the function, then we should decide on how to deal with NA values. In most cases these will be because the fecundity was not measured, but we know that SOME fecundity happened. Therefore, since the key is to simply identify which stages have fecundity, one can replace the NA with e.g. Inf, and then remove this in the rearranged matrix.

What do you think?

**Comment by tdjames1** [comment] 2017-07-17 12:06
Thanks for looking at this. You're right, the error is thrown by an operation on matFmu; I'd supplied an identical matF and matFmu in this case because we don't have individual matrices over which to calculate a mean fecundity matrix.

I think that the function should check/warn about dubious inputs. Your suggestion of replacing with Inf is neat but it does leave the problem of NA in matFmu to the next function in the chain (reprodStages()) which will also fail because it does something similar with matFmu. We could get around that by passing on the matFmu with Infs in place.

**Closed** 2017-07-19 07:12 UTC
